name: Check Build success

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build EVC:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build evc
        run: make evc
  build RBC:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build rbc
        run: make rbc
